/**
 * \file Opcode.h
 *
 * Enumeration of all instruction opcodes supported by SIMEX.
 *
 * Copyright (C) 2016 Justin Handville - All Rights Reserved.
 *
 * This file is part of the SIMEX Virtual Machine which is released under the
 * MIT License.  See LICENSE.txt in the root of this distribution for further
 * information.
 */

#ifndef  SIMEX_OPCODE_HEADER_GUARD
# define SIMEX_OPCODE_HEADER_GUARD

#include <cstdint>

//this header is C++ specific
#ifdef __cplusplus

namespace simex {

/**
 * The Opcode Enumeration contains all opcodes supported by SIMEX.
 */
enum class Opcode : std::uint8_t
{
    OP_SYSCALL          =   0x00,
    OP_FCMP             =   0x01,
    OP_FUN              =   0x02,
    OP_FEQL             =   0x03,
    OP_FADD             =   0x04,
    OP_FIX              =   0x05,
    OP_FSUB             =   0x06,
    OP_FIXU             =   0x07,
    OP_FLOT             =   0x08,
    OP_FLOTI            =   0x09,
    OP_FLOTU            =   0x0A,
    OP_FLOTUI           =   0x0B,
    OP_SFLOT            =   0x0C,
    OP_SFLOTI           =   0x0D,
    OP_SFLOTU           =   0x0E,
    OP_SFLOTUI          =   0x0F,
    OP_FMUL             =   0x10,
    OP_FCMPE            =   0x11,
    OP_FUNE             =   0x12,
    OP_FEQLE            =   0x13,
    OP_FDIV             =   0x14,
    OP_FSQRT            =   0x15,
    OP_FREM             =   0x16,
    OP_FINT             =   0x17,
    OP_MUL              =   0x18,
    OP_MULI             =   0x19,
    OP_MULU             =   0x1A,
    OP_MULUI            =   0x1B,
    OP_DIV              =   0x1C,
    OP_DIVI             =   0x1D,
    OP_DIVU             =   0x1E,
    OP_DIVUI            =   0x1F,
    OP_ADD              =   0x20,
    OP_ADDI             =   0x21,
    OP_ADDU             =   0x22,
    OP_ADDUI            =   0x23,
    OP_SUB              =   0x24,
    OP_SUBI             =   0x25,
    OP_SUBU             =   0x26,
    OP_SUBUI            =   0x27,
    OP_2ADDU            =   0x28,
    OP_2ADDUI           =   0x29,
    OP_4ADDU            =   0x2A,
    OP_4ADDUI           =   0x2B,
    OP_8ADDU            =   0x2C,
    OP_8ADDUI           =   0x2D,
    OP_16ADDU           =   0x2E,
    OP_16ADDUI          =   0x2F,
    OP_CMP              =   0x30,
    OP_CMPI             =   0x31,
    OP_CMPU             =   0x32,
    OP_CMPUI            =   0x33,
    OP_NEG              =   0x34,
    OP_NEGI             =   0x35,
    OP_NEGU             =   0x36,
    OP_NEGUI            =   0x37,
    OP_SL               =   0x38,
    OP_SLI              =   0x39,
    OP_SLU              =   0x3A,
    OP_SLUI             =   0x3B,
    OP_SR               =   0x3C,
    OP_SRI              =   0x3D,
    OP_SRU              =   0x3E,
    OP_SRUI             =   0x3F,
    OP_BN               =   0x40,
    OP_BNB              =   0x41,
    OP_BZ               =   0x42,
    OP_BZB              =   0x43,
    OP_BP               =   0x44,
    OP_BPB              =   0x45,
    OP_BOD              =   0x46,
    OP_BODB             =   0x47,
    OP_BNN              =   0x48,
    OP_BNNB             =   0x49,
    OP_BNZ              =   0x4A,
    OP_BNZB             =   0x4B,
    OP_BNP              =   0x4C,
    OP_BNPB             =   0x4D,
    OP_BEV              =   0x4E,
    OP_BEVB             =   0x4F,
    OP_PBN              =   0x50,
    OP_PBNB             =   0x51,
    OP_PBZ              =   0x52,
    OP_PBZB             =   0x53,
    OP_PBP              =   0x54,
    OP_PBPB             =   0x55,
    OP_PBOD             =   0x56,
    OP_PBODB            =   0x57,
    OP_PBNN             =   0x58,
    OP_PBNNB            =   0x59,
    OP_PBNZ             =   0x5A,
    OP_PBNZB            =   0x5B,
    OP_PBNP             =   0x5C,
    OP_PBNPB            =   0x5D,
    OP_PBEV             =   0x5E,
    OP_PBEVB            =   0x5F,
    OP_CSN              =   0x60,
    OP_CSNI             =   0x61,
    OP_CSZ              =   0x62,
    OP_CSZI             =   0x63,
    OP_CSP              =   0x64,
    OP_CSPI             =   0x65,
    OP_CSOD             =   0x66,
    OP_CSODI            =   0x67,
    OP_CSNN             =   0x68,
    OP_CSNNI            =   0x69,
    OP_CSNZ             =   0x6A,
    OP_CSNZI            =   0x6B,
    OP_CSNP             =   0x6C,
    OP_CSNPI            =   0x6D,
    OP_CSEV             =   0x6E,
    OP_CSEVI            =   0x6F,
    OP_ZSN              =   0x70,
    OP_ZSNI             =   0x71,
    OP_ZSZ              =   0x72,
    OP_ZSZI             =   0x73,
    OP_ZSP              =   0x74,
    OP_ZSPI             =   0x75,
    OP_ZSOD             =   0x76,
    OP_ZSODI            =   0x77,
    OP_ZSNN             =   0x78,
    OP_ZSNNI            =   0x79,
    OP_ZSNZ             =   0x7A,
    OP_ZSNZI            =   0x7B,
    OP_ZSNP             =   0x7C,
    OP_ZSNPI            =   0x7D,
    OP_ZSEV             =   0x7E,
    OP_ZSEVI            =   0x7F,
    OP_LDB              =   0x80,
    OP_LDBI             =   0x81,
    OP_LDBU             =   0x82,
    OP_LDBUI            =   0x83,
    OP_LDW              =   0x84,
    OP_LDWI             =   0x85,
    OP_LDWU             =   0x86,
    OP_LDWUI            =   0x87,
    OP_LDT              =   0x88,
    OP_LDTI             =   0x89,
    OP_LDTU             =   0x8A,
    OP_LDTUI            =   0x8B,
    OP_LDO              =   0x8C,
    OP_LDOI             =   0x8D,
    OP_LDOU             =   0x8E,
    OP_LDOUI            =   0x8F,
    OP_LDSF             =   0x90,
    OP_LDSFI            =   0x91,
    OP_LDHT             =   0x92,
    OP_LDHTI            =   0x93,
    OP_CSWAP            =   0x94,
    OP_CSWAPI           =   0x95,
    OP_LDUNC            =   0x96,
    OP_LDUNCI           =   0x97,
    OP_RESERVED_x98     =   0x98,
    OP_RESERVED_x99     =   0x99,
    OP_RESERVED_x9A     =   0x9A,
    OP_RESERVED_x9B     =   0x9B,
    OP_RESERVED_x9C     =   0x9C,
    OP_RESERVED_x9D     =   0x9D,
    OP_GO               =   0x9E,
    OP_GOI              =   0x9F,
    OP_STB              =   0xA0,
    OP_STBI             =   0xA1,
    OP_STBU             =   0xA2,
    OP_STBUI            =   0xA3,
    OP_STW              =   0xA4,
    OP_STWI             =   0xA5,
    OP_STWU             =   0xA6,
    OP_STWUI            =   0xA7,
    OP_STT              =   0xA8,
    OP_STTI             =   0xA9,
    OP_STTU             =   0xAA,
    OP_STTUI            =   0xAB,
    OP_STO              =   0xAC,
    OP_STOI             =   0xAD,
    OP_STOU             =   0xAE,
    OP_STOUI            =   0xAF,
    OP_STSF             =   0xB0,
    OP_STSFI            =   0xB1,
    OP_STHT             =   0xB2,
    OP_STHTI            =   0xB3,
    OP_STCO             =   0xB4,
    OP_STCOI            =   0xB5,
    OP_STUNC            =   0xB6,
    OP_STUNCI           =   0xB7,
    OP_RESERVED_xB8     =   0xB8,
    OP_RESERVED_xB9     =   0xB9,
    OP_RESERVED_xBA     =   0xBA,
    OP_RESERVED_xBB     =   0xBB,
    OP_RESERVED_xBC     =   0xBC,
    OP_RESERVED_xBD     =   0xBD,
    OP_PUSHGO           =   0xBE,
    OP_PUSHGOI          =   0xBF,
    OP_OR               =   0xC0,
    OP_ORI              =   0xC1,
    OP_ORN              =   0xC2,
    OP_ORNI             =   0xC3,
    OP_NOR              =   0xC4,
    OP_NORI             =   0xC5,
    OP_XOR              =   0xC6,
    OP_XORI             =   0xC7,
    OP_AND              =   0xC8,
    OP_ANDI             =   0xC9,
    OP_ANDN             =   0xCA,
    OP_ANDNI            =   0xCB,
    OP_NAND             =   0xCC,
    OP_NANDI            =   0xCD,
    OP_NXOR             =   0xCE,
    OP_NXORI            =   0xCF,
    OP_RESERVED_xD0     =   0xD0,
    OP_RESERVED_xD1     =   0xD1,
    OP_RESERVED_xD2     =   0xD2,
    OP_RESERVED_xD3     =   0xD3,
    OP_RESERVED_xD4     =   0xD4,
    OP_RESERVED_xD5     =   0xD5,
    OP_RESERVED_xD6     =   0xD6,
    OP_RESERVED_xD7     =   0xD7,
    OP_MUX              =   0xD8,
    OP_MUXI             =   0xD9,
    OP_RESERVED_xDA     =   0xDA,
    OP_RESERVED_xDB     =   0xDB,
    OP_RESERVED_xDC     =   0xDC,
    OP_RESERVED_xDD     =   0xDD,
    OP_RESERVED_xDE     =   0xDE,
    OP_RESERVED_xDF     =   0xDF,
    OP_SETH             =   0xE0,
    OP_SETMH            =   0xE1,
    OP_SETML            =   0xE2,
    OP_SETL             =   0xE3,
    OP_INCH             =   0xE4,
    OP_INCMH            =   0xE5,
    OP_INCML            =   0xE6,
    OP_INCL             =   0xE7,
    OP_ORH              =   0xE8,
    OP_ORMH             =   0xE9,
    OP_ORML             =   0xEA,
    OP_ORL              =   0xEB,
    OP_ANDNH            =   0xEC,
    OP_ANDNMH           =   0xED,
    OP_ANDNML           =   0xEE,
    OP_ANDNL            =   0xEF,
    OP_JMP              =   0xF0,
    OP_JMPB             =   0xF1,
    OP_PUSHJ            =   0xF2,
    OP_PUSHJB           =   0xF3,
    OP_GETA             =   0xF4,
    OP_GETAB            =   0xF5,
    OP_PUT              =   0xF6,
    OP_PUTI             =   0xF7,
    OP_POP              =   0xF8,
    OP_RESUME           =   0xF9,
    OP_SAVE             =   0xFA,
    OP_UNSAVE           =   0xFB,
    OP_SYNC             =   0xFC,
    OP_SWYM             =   0xFD,
    OP_GET              =   0xFE,
    OP_RESERVED_xFF     =   0xFF
};

/**
 * Convert an Opcode to a byte.
 *
 * \param op        The opcode to convert.
 *
 * \returns the converted opcode as a byte.
 */
inline uint8_t opcode2byte(Opcode op)
{
    //explicit conversion to the uint8_t type.
    return static_cast<std::underlying_type<Opcode>::type>(op);
}

/* namespace simex */}

//end of C++ specific section
#endif //__cplusplus

#endif //SIMEX_OPCODE_HEADER_GUARD
